version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0
    command: --log_bin_trust_function_creators=1 --default-authentication-plugin=mysql_native_password
    volumes:
      - datadir:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${ARTIFAKT_MYSQL_DATABASE_NAME}
      MYSQL_USER: ${ARTIFAKT_MYSQL_USER}
      MYSQL_PASSWORD: ${ARTIFAKT_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
      - "3306:3306"

  redis:
    image: redis:6-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    image: base-shopware
    ports:
      - "80:80"
    volumes:
      - data:/data
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET}
      APP_URL: ${APP_URL}
      ARTIFAKT_MYSQL_HOST: ${ARTIFAKT_MYSQL_HOST}
      ARTIFAKT_MYSQL_DATABASE_NAME: ${ARTIFAKT_MYSQL_DATABASE_NAME}
      ARTIFAKT_MYSQL_USER: ${ARTIFAKT_MYSQL_USER}
      ARTIFAKT_MYSQL_PASSWORD: ${ARTIFAKT_MYSQL_PASSWORD}
      ARTIFAKT_MYSQL_PORT: ${ARTIFAKT_MYSQL_PORT}
      DATABASE_HOST: ${ARTIFAKT_MYSQL_HOST}
      DATABASE_PASSWORD: ${ARTIFAKT_MYSQL_PASSWORD}
      DATABASE_URL: mysql://${ARTIFAKT_MYSQL_USER}:${ARTIFAKT_MYSQL_PASSWORD}@${ARTIFAKT_MYSQL_HOST}:${ARTIFAKT_MYSQL_PORT}/${ARTIFAKT_MYSQL_DATABASE_NAME}
      DATABASE_USER: ${ARTIFAKT_MYSQL_USER}
      INSTALL_ADMIN_PASSWORD: ${INSTALL_ADMIN_PASSWORD}
      INSTALL_ADMIN_USERNAME: ${INSTALL_ADMIN_USERNAME}
      INSTALL_LOCALE: ${INSTALL_LOCALE}
      INSTALL_STOREFRONT_NAME: ${INSTALL_STOREFRONT_NAME}
      INSTANCE_ID: ${INSTANCE_ID}
      MAILER_URL: ${MAILER_URL}
      PHP_CONF_DATE_TIMEZONE: "Europe/Berlin"
      PHP_CONF_MAX_EXECUTION_TIME: 180
      PHP_CONF_MEMORY_LIMIT: "-1"
      PHP_CONF_OPCACHE_VALIDATE_TIMESTAMP: 1
      REDIS_SESSION_DATABASE: ${REDIS_SESSION_DATABASE}
      REDIS_SESSION_HOST: ${REDIS_SESSION_HOST}
      REDIS_SESSION_PORT: ${REDIS_SESSION_PORT}
      SHOPWARE_ES_ENABLED: ${SHOPWARE_ES_ENABLED}
      # SHOPWARE_ES_HOSTS: ${SHOPWARE_ES_HOSTS}
      # SHOPWARE_ES_INDEX_PREFIX: ${SHOPWARE_ES_INDEX_PREFIX}
      # SHOPWARE_ES_INDEXING_ENABLED: ${SHOPWARE_ES_INDEXING_ENABLED}
      SHOPWARE_HTTP_CACHE_ENABLED: ${SHOPWARE_HTTP_CACHE_ENABLED}
      SHOPWARE_HTTP_DEFAULT_TTL: ${SHOPWARE_HTTP_DEFAULT_TTL}
    depends_on:
      - mysql
      - redis


volumes:
  data:
  datadir: