version: '3'
services:
  database:
    image: mysql/mysql-server:8.0
    command: --log_bin_trust_function_creators=1 --default-authentication-plugin=mysql_native_password
    volumes:
      - datadir:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
      - "3306:3306"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes      
  app:
    build: .
    image: base-symfony
    ports:
      - "80:80"
    volumes:
      - data:/data
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_CONF_MEMORY_LIMIT: "-1"
      PHP_CONF_DATE_TIMEZONE: "Europe/Berlin"
      PHP_CONF_MAX_EXECUTION_TIME: 180
      PHP_CONF_OPCACHE_VALIDATE_TIMESTAMP: 1
      APP_SECRET: ${APP_SECRET}
      INSTANCE_ID: ${INSTANCE_ID}
      APP_URL: ${APP_URL}
      MAILER_URL: ${MAILER_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_URL: "mysql://shopware:shopware@database:3306/shopware"
      SHOPWARE_ES_HOSTS: ${SHOPWARE_ES_HOSTS}
      SHOPWARE_ES_ENABLED: ${SHOPWARE_ES_ENABLED}
      SHOPWARE_ES_INDEXING_ENABLED: ${SHOPWARE_ES_INDEXING_ENABLED}
      SHOPWARE_ES_INDEX_PREFIX: ${SHOPWARE_ES_INDEX_PREFIX}
      SHOPWARE_HTTP_CACHE_ENABLED: ${SHOPWARE_HTTP_CACHE_ENABLED}
      SHOPWARE_HTTP_DEFAULT_TTL: ${SHOPWARE_HTTP_DEFAULT_TTL}
      INSTALL_LOCALE: ${INSTALL_LOCALE}
      INSTALL_ADMIN_USERNAME: admin
      INSTALL_ADMIN_PASSWORD: shopware
      REDIS_SESSION_HOST: ${REDIS_SESSION_HOST}
      REDIS_SESSION_PORT: ${REDIS_SESSION_PORT}
      REDIS_SESSION_DATABASE: ${REDIS_SESSION_DATABASE}
    depends_on: 
      - database
      - redis


volumes: 
  data:
  datadir: